### ISSUE TITLE
Analysis of stranded vs unstranded RNA-seq data

### ISSUE THREAD

**Issue by lianos** [splicebox/MntJULiP#10]
Greetings,

I was wondering if there was any specific considerations to take when using MntJULiP to analyze short read RNA-seq data from a stranded vs unstranded library prep protocol?

**Comment by splicebox** [comment]
Hello @lianos - thanks for trying out MntJULiP. There are no special considerations regarding stranded versus unstranded protocols, the algorithm uses the strand information in the alignment file for introns. So, please make sure this information is included in the BAM file (for instance, when running STAR please use the --outSAMstrandField intronMotif option).

**Comment by lianos** [comment]
Great, thank you for the quick response!
