### ISSUE TITLE
Update installation instructions to install from GitHub repo

### ISSUE THREAD

**Issue by lianos** [splicebox/MntJULiP#11]
I tried to follow the installation instructions for the latest version of MntJULiP from the GitHub repository and ran into a few problems. I've got it cooking on a pretty large dataset and things look like they're doing OK, but thought I'd make a note of it here to see if either the documentation should be updated, or if I need to fix something in my environment.

Currently the installation instructions tell us to:

```bash
cd MnJULiP
conda env create -f mntjulip_cov.yml
#  run setup.py to install MntJULiP and all the required packages
module load cmake
python3 setup.py install  
```
I'm running on conda version 24.3.0, and the first issue I ran into was that running the `conda env create -f mntjulip_cov.yml` command didn't work out of the box. I had to update the `channel_priority` to `"flexible"` (from its `"strict"` default) in order for it to work. So, this is what I needed to do in order to create the MntJULiP conda environment:

```bash
$ conda config --set channel_priority flexible
$ conda env create -f mntjulip_cov.yml
```

The `module load cmake` command is likely soething unique to your compute cluster, so probably not necessary for most people that have a standard build tool chain involved, but I also had to install `Cython` into the conda environment.  After that, things seemed to work out just fine.

So, this is what I had to do more or less to get MntJULiP installed from github start to finish.

```bash
(base) $ git clone https://github.com/splicebox/MntJULiP.git
(base) $ cd MntJULiP
(base) $ conda config --set channel_priority flexible
(base) $ conda env create -f mntjulip_cov.yml
(base) $ conda activate mj-cov
(mj-cov) $ conda install cython
(mj-cov)$ python setup.py install
# compile in progress
# now `run.py` seems to work as expected
(mj-cov)$ python run.py --help
```

It's been a while since I dug deep into the world of administering python environments, but perhaps adding `cython` into the `mntjulip_cov.yml` could be useful to make the installation steps a bit easier? Also, the current installation steps don't point out that you have to activate the environment you created with `conda env create ...` before trying to run `python setup.py install` from within the MntJULiP repo, but I'm *pretty sure* you're going to have to do that.

Thanks!

**Comment by edwwlui** [comment]
Thank you for your time in trying out MntJULiP and providing such detailed suggestions!

**Comment by lianos** [comment]
Well, thanks for providing such useful software!

I see you updated the README, however it still might be useful to note that users may need to run `conda config --set channel_priority flexible` if they run into problems running `conda env create -f mntjulip_cov.yml`

Thanks again!
