### ISSUE TITLE
fillna() got an unexpected keyword argument 'inplace'

### ISSUE THREAD

**Issue by Yangliu9ReviR** [splicebox/MntJULiP#13]
Hi guys, thanks for the nice tool to quantify splicing. When I ran the code this morning, it raised the following error:

`Traceback (most recent call last):
  File "/usr/local/MntJULiP/run.py", line 161, in <module>
    main()
  File "/usr/local/MntJULiP/run.py", line 120, in main
    df, index_df, anno_intron_dict = process_introns_with_annotation(out_data_dir, num_samples, anno_intron_dict, start_site_genes_dict,
  File "/usr/local/MntJULiP/utils.py", line 195, in process_introns_with_annotation
    df.fillna(0, inplace=True)
TypeError: fillna() got an unexpected keyword argument 'inplace'`

Any suggestions?

**Comment by edwwlui** [comment]
Hi Yangliu, thanks for using MntJULiP! I am unable to reproduce the error, it'd be great if I can have your input data. In the meantime, you might try the following workaround:
```
#  replace df.fillna(0, inplace=True) with:
df=df.fillna(0)
```

**Comment by Yangliu9ReviR** [comment]
Thanks! I'll try it first.

**Comment by Yangliu9ReviR** [comment]
Removing inplace argument does not work. I guess it's the compatibility issue of dask and pandas dataframe. Now I have python = 3.9, pandas==2.2.2 and dask==2024.5.2. Do you have any suggestions for the version?

**Comment by edwwlui** [comment]
Thanks for letting us know. My tested environment has pandas==1.3.5, dask==2022.2.0 and python 3.7.

**Comment by Yangliu9ReviR** [comment]
In Python 3.9, the default package version of dask and numpy is too high for Mntjulip. I'll downgrade to Python 3.7 and see what it looks like. Thanks!

**Comment by Yangliu9ReviR** [comment]
Python 3.7 with default versions works. I'll close the issue.
```
pandas==1.3.5
scipy==1.7.3
dask==2022.2.0
numpy==1.21.6
```
